version: '3'
services:
    mypinger:
        build:
            context: .
            dockerfile: pinger.dockerfile
        image: pinger
        container_name: mypinger
        restart: always
        env_file:
            - ./pinger.env
        volumes:
            - "C:\\temp\\pinger\\:/var/log/pinger/:z" 